version: "3.9"

services:
  web:
    build: 
      context: ./typescript/simple-mercari-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - .env
    depends_on:
      - app

  app:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - .env
